name: Django Workflow

on:
  push:
    branches:
      - egc_test
  pull_request:
    branches:
      - egc_test

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        postgres-version: [14.9, 15]

    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_USER: decide
          POSTGRES_PASSWORD: decide
          POSTGRES_DB: decide
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U decide" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12
    - name: psycopg2 prerequisites
      run: sudo apt-get install libpq-dev
    - name: Install dependencies and config
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cp decide/local_settings.gactions.py decide/local_settings.py
    - name: Run migrations
      run: |
        cd decide
        python manage.py migrate
    - name: Run tests without coverage
      run: |
        cd decide
        python manage.py test --keepdb
